news api
SeR4h/andelaweek4challenge pull request #1
Opened 2019-12-12 13:17 UTC by SeR4h

@billkabanga please review my code.

2019-12-17 18:24 UTC, SeR4h commented
@dennisja please review my code

2019-12-18 19:48 UTC, dennisja requested changes
There is a lot of work to do on this, I will add more comments tomorrow

2019-12-18 19:48 UTC, dennisja commented on package.json
> +    "cross-fetch": "^3.0.4",
You have `cross-fetch` and `node-fetch` dependencies but you are not using them anywhere, please remove them

2019-12-18 19:48 UTC, dennisja commented on package.json
> +}
Newline at End of file

2019-12-20 07:53 UTC, dennisja requested changes
First, make these changes, I'm going to show you how we can get rid of the many if statements, But usually instead of making many `if..else` statements, It is better to use a `switch` statement for readability

2019-12-20 07:53 UTC, dennisja commented on index.js
> +console.log('Welcome to our news application');
Instead of using multiple console logs we can put all these strings in one string which we cal logout once or even use as the first argument of `rl.question`. We can do so by making use of template [literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)
```js
// Example of a template literal
const sampleLiteral = `This is an example of a template literal
This will appear on a new line if this string is logged out. No need of the "\n" escape character
This is another line
`

```

2019-12-20 07:53 UTC, dennisja commented on index.js
> +        Request.get("https://newsapi.org/v2/top-headlines?sources=abc-news&apiKey=e1f6aaadd26d4ced846348e1222b23d7", (error, response, body) => {
This code appears multiple times, It is better we extract it into a function i.e
Create a function that takes a news source and returns the top 10 headlines for that source
```js
function getTopHeadlines(newsSource){
// how you can combine strings using template literals
const url = `https://nap.org?sources=${newsSource}`
Request.get(url, ()=>{
// do your stuff here
})
}

// You can later on go ahead and call this function for every news source like
getTopHeadlines('abc-news')
```

2019-12-20 07:53 UTC, dennisja commented on index.js
> +console.log('Welcome to our news application');
You can even concatenate two string using template literals e.g
```js
// given two sting
const a = `firstString`;
const b = `and secondString`;

// you can concatenate them by using the + operator
const aAndB = a + ' ' + b;

// or you can use the template literals
const aAndB = `${a} ${b}`;
```

2019-12-21 13:51 UTC, SeR4h commented
@dennisja please review 'News api with corrections'

2019-12-22 16:33 UTC, dennisja requested changes

2019-12-22 16:33 UTC, dennisja commented on index.js
> +rl.question('Type option: ', function (option) {
Add `Type option: ` to the `welcomeMessage` variable and pass the variable as the first argument of `rl.question` instead of logging it out

2019-12-22 16:33 UTC, dennisja commented on index.js
> +    if (option === '1') {
Shorten this code by:
```js
// create an object where the number of a news source is the key and the value is an object containing the name and id of the source i.e
const sources = {
 "1": {
     name: "ABC News",
     id: "abc-news"
  }
  // add other sources here
}
// create the above object outside of the callback you are passing to rl.question

// in the rl.question callback
// check whether the asked news source exists and throw an error if not
if(option in sources){
  console.log(sources[option].name)
   getTopHeadLines(sources[option].id)
}else{
   throw new Error('Invalid Input')
}
```

2019-12-22 16:33 UTC, dennisja commented
First, work on those and we will see how to improve this

2019-12-26 18:40 UTC, SeR4h commented
@dennisja please review 'new changes' to see improvements

2019-12-27 16:44 UTC, dennisja requested changes

2019-12-27 16:44 UTC, dennisja commented on index.js
> +const welcomeMessage = `Welcome to our news application
Leave a line before this

2019-12-27 16:44 UTC, dennisja commented on index.js
> +});
Leave a line after this.
Always leave a line before and after a function for readability purposes

2019-12-27 16:44 UTC, dennisja commented on index.js
> +        console.log(JSON.parse(body));
You are logging out a full object which is not what you are supposed to do
You have to access the articles array, loop through it and extract the title, content, and URL for each headline and log those out.
First try it out and I will advise you on how to improve it

2019-12-27 16:44 UTC, dennisja commented on index.js
> +const sources = {
Please change the sources key to have the source index as the key and the source id as the value
i.e
```js
const sourceKeys = {
 "1": "abc-news",
 // put the rest here
}
```

2019-12-27 16:44 UTC, dennisja commented on index.js
> +        console.log(JSON.parse(body));
You can as well access the source Id and name and log them out, they are there in the response

2019-12-27 16:44 UTC, dennisja commented on index.js
> +        console.log(sources[option].name);
Remove this console log. logout the name of the source from the response you get in `getTopHeadlines`

2019-12-27 16:44 UTC, dennisja commented on index.js
> +        getTopheadlines(sources[option].id);
If you change the value of  `sources` object to be the sourceId, you will have to change this as well

2019-12-27 17:16 UTC, dennisja commented on index.js
> +    const apiKey = `e1f6aaadd26d4ced846348e1222b23d7`;
It is also not good to expose your API keys since most of them are private and are what API owners use to identify their users. Someone else can use your API key to do something un desireable. A workaround is to set it as an environment variable and access it using `process.env.VARIABLE_NAME` if you set it as `VARIABLE_NAME`. 
You can set environment variables in python using `set` eg.
```sh
set VARIABLE_NAME=VARIABLE_VALUE
```

2019-12-27 19:22 UTC, SeR4h commented
@dennisja please review ''modified api with environment variable'

2019-12-27 20:07 UTC, dennisja requested changes

2019-12-27 20:07 UTC, dennisja commented on index.js
> +const newsSource = [];
Avoid creating variables outside a function body if you are to use them in a function

2019-12-27 20:07 UTC, dennisja commented on index.js
> +        for (var i = 0; i < 10; i++) {
Instead of using 10, please use the length of the articles array i.e `for(var i = 0; i < aources.articles.length; i++)`

2019-12-27 20:07 UTC, dennisja commented on index.js
> +        const sources = JSON.parse(body);
JavaScript has a feature called destructuring, You can either destructure an object or an array.
You will use destructuring to access the articles array and the source name
An example of destructuring
```js
// object destructuring
// given an object below
const z = { a: 12, b: [1,2,3], c: [{x: 13, d, 13}]}

// instead of accessing a, b and c like z.c, z.b, z.c
// we can destructure them and access them directly
const {a, b, c} = z; // note: The names used when destructuring an object corresponding to the keys in the object
// we can use a, b, and c here. If we only need to use a, and b we could only destructure a and b

// array destructuring
// we can destructure array two by index i.e
// given an array below
const z = [1, 2, 3, 4]
// we can access the first two variables using destructuring like
const [first, second] = z

// a usefull example
// if a value in the array is an object, we can nest object destructing in an array destructuring to get a key from that object
// given 
const s = [{a: 12, b: 13}, {a: 1, b: 2}]
// instead of
console.log(s[0].a)
// we can destructure a and log it directly by combining array and object destructuring
const [{a}] = s
console.log(a)
```

You can read more about destructuring [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

2019-12-27 20:07 UTC, dennisja commented on index.js
> +        for (var i = 0; i < 10; i++) {
Instead of a for loop. Most of the time if you find yourself creating a new array from an existing array it's at times better to use the map method.
Forexample
```js
// given an array of numbers from one to 5
const z = [1,2,3,4,5];

// if we are required to create an array of the squares of each number
// if we are to use the map method of arrays, we will end up with
const squares = z.map(number=>number**2)
```
Read more about map [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) and see how you can combine it with destructuring to crate a new array with only title, content, and url from the fetched articles array

2019-12-29 15:58 UTC, SeR4h commented
@dennisja please review 'api modification'

2019-12-29 21:22 UTC, dennisja requested changes
Hey, Thanks for the attempt.
Try out the new suggestions

2019-12-29 21:22 UTC, dennisja commented on index.js
> +        const sources = JSON.parse(body);
Instead of doing this, we can access the articles array using destructuring
```js
// accessing articles array using destructuring
const { articles } = JSON.parse(body);
// we can use the articles array here

// we can also access the source name using destructuring i.e access source name of the first article
const [{ source: { name }}] = articles
// we can use the name variable below, Its the name of the news source whose headlines are fetched
```

2019-12-29 21:22 UTC, dennisja commented on index.js
> +        const newsSource = sources.articles.map(x => x)
Map the articles array to an array of string representations of each article forexample
```js
const articlesTextArray = articles.map((article, articleIndex)=>`${articleIndex} ${article.title}
${article.content}
Read More: ${article.url}
`); // feel free to change the format of the string


// after this, covert the articles text array using the join method and new line as a seperator into a single string
// concate the source name and the articles string and log them out i.e
const headlines = `${articleSourceName}
${articleString}
`
console.log(headlines)
```

2019-12-30 15:42 UTC, SeR4h commented
@dennisja please review ''news api'' with new suggestions

2019-12-30 16:09 UTC, dennisja approved these changes
Merge this but, 
Create another PR where you should
1. Write a readme file explaining
- How someone should set up and run your work
- How someone should add environment variables
2. Add a sample .env file, you can name it `.env-example` where you should explain the environment variables used
3. Add a `.gitignore` file and include all paths to files and folders you don't want to appear in version control

2019-12-30 16:09 UTC, dennisja commented on index.js
> +        const articleString = articlesArray.join('\n');
You can even use two newline characters to make the articles readable

2019-12-30 16:13 UTC, dennisja commented on index.js
> +        const [{ source: { name: sourceName } }] = articles;
Well done on renaming this 🙂

2019-12-30 16:14 UTC, dennisja commented on index.js
> +        const [{ source: { name: sourceName } }] = articles;
You can by the way move line 17-24 to a separate function that takes the articles array and returns you a string you can logot

2019-12-30 17:37 UTC, merged

2019-12-31 10:05 UTC, dennisja commented on index.js
> +    return console.log(headlines)
Just return `headlines`.
And use `getHeadlines` like
```js
const headlines = getHeadlines(articles)
console.log(headlines)
```

The result of console.log is undefined