Readme
SeR4h/andelaweek4challenge pull request #2
Opened 2019-12-30 19:08 UTC by SeR4h

@dennisja Please review these files

2019-12-31 10:55 UTC, dennisja requested changes

2019-12-31 10:55 UTC, dennisja commented on .gitignore
> +node_modules/
Add a new line at the end of this file

2019-12-31 10:55 UTC, dennisja commented on .env-example
> +#this project uses the apiKey environment variable
These comments are very many just add like one comment which explains the purpose of the file and explain each environment variable with a comment on top.
e.g
```sh
# A sample file containing some of the environment variables you will need to set the application

# The API key is given after registering to use the News API
API_KEY=YOUR_NEWS_API_KEY
```

2019-12-31 10:55 UTC, dennisja commented on README.md
> +Consuming a news api(node.js)
These instructions are wrong. Can you look at [this ](https://github.com/dennisja/some-tweets/blob/master/README.md) or [this](https://github.com/dennisja/react-tips-and-patterns/blob/master/README.md) and see how you can improve your readme.

You are going to use Markdown to write the Readme. Read about how to format your readme [here](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax)

2020-01-07 15:28 UTC, SeR4h commented
@dennisja please review additionalFiles

2020-01-08 09:01 UTC, dennisja commented on README.md
> +npm install request --save
Hey @SeR4h 
Well done on this.
All a person needs to do when they clone your project to install your dependencies is to just run 
```sh
npm install
```
No need to install them seperately

2020-01-08 09:02 UTC, dennisja approved these changes
Change the instructions for installing dependencies and merge

2020-01-08 13:53 UTC, merged